# Generated by Django 3.1.3 on 2020-12-11 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentOperationNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_operation_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OperateAvatarMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_operation_number', models.PositiveIntegerField()),
                ('o_avater_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='part',
            name='p_selected',
        ),
        migrations.AddConstraint(
            model_name='avatar',
            constraint=models.UniqueConstraint(fields=('a_number', 'a_category'), name='category_unique'),
        ),
        migrations.AddField(
            model_name='operateavatarmemory',
            name='o_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AddField(
            model_name='operateavatarmemory',
            name='o_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.part'),
        ),
    ]
